name: mobilsharelocation
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  #advanced_splashscreen: ^0.0.1
  animated_splash: ^1.0.0
  cupertino_icons: ^0.1.2
  provider: ^3.2.0
  geolocator: ^5.1.5
  get_it: ^3.0.3
  google_maps_flutter: ^0.5.21+15
  share: ^0.6.3+5
  geocoder: ^0.2.1
  loading_animations: "^2.1.0"
  flutter_staggered_animations: ^0.1.2

  
  
  
dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:


  uses-material-design: true

  assets:
    - assets/images/
 
  fonts:
    - family: InriaSerif
      fonts:
      - asset: assets/fonts/InriaSerif-Regular.ttf
 
    - family: IndieFlower
      fonts:
        - asset: assets/fonts/IndieFlower-Regular.ttf
        
    - family: CourierPrime
      fonts:
        - asset: assets/fonts/CourierPrime-Regular.ttf

    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
      
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf

  

